SET SQL DIALECT 3;
/* (6) Table with NO primary key */
CREATE TABLE NOPK_LOG (
  LOG_TS    TIMESTAMP,
  MESSAGE   VARCHAR(200)
);

/* (8) Over-indexed write-heavy table: 6 single-column indexes */
CREATE TABLE OVERIDX (
  ID    INTEGER NOT NULL PRIMARY KEY,
  A INTEGER, B INTEGER, C INTEGER, D INTEGER, E INTEGER, F INTEGER
);
CREATE INDEX IDX_OVERIDX_A ON OVERIDX (A);
CREATE INDEX IDX_OVERIDX_B ON OVERIDX (B);
CREATE INDEX IDX_OVERIDX_C ON OVERIDX (C);
CREATE INDEX IDX_OVERIDX_D ON OVERIDX (D);
CREATE INDEX IDX_OVERIDX_E ON OVERIDX (E);
CREATE INDEX IDX_OVERIDX_F ON OVERIDX (F);

/* (7) Stale statistics: index created on the EMPTY table, rows inserted afterwards. */
CREATE TABLE STALE_T (
  ID   INTEGER NOT NULL PRIMARY KEY,
  CODE INTEGER
);
CREATE INDEX IDX_STALE_CODE ON STALE_T (CODE);
COMMIT;

SET TERM ^ ;
EXECUTE BLOCK AS DECLARE I INTEGER = 0; BEGIN
  WHILE (I < 4000) DO BEGIN
    INSERT INTO STALE_T (ID, CODE) VALUES (:I, :I);
    INSERT INTO OVERIDX (ID, A, B, C, D, E, F) VALUES (:I, MOD(:I,2), MOD(:I,3), :I, :I, :I, :I);
    I = I + 1;
  END
END^
SET TERM ; ^
COMMIT;

/* (10) Non-sargable: query will use LIKE '%foo' / fn(col); table just needs data */
CREATE TABLE NSARG_T (ID INTEGER NOT NULL PRIMARY KEY, NAME VARCHAR(100));
CREATE INDEX IDX_NSARG_NAME ON NSARG_T (NAME);

/* (11) Implicit conversion: INTEGER column queried with a string literal */
CREATE TABLE CONV_T (ID INTEGER NOT NULL PRIMARY KEY, CODE INTEGER);
CREATE INDEX IDX_CONV_CODE ON CONV_T (CODE);

/* (12) Oversized index key: long VARCHAR indexed (key-size pressure on small page sizes) */
CREATE TABLE BIGKEY_T (ID INTEGER NOT NULL PRIMARY KEY, LABEL VARCHAR(800) CHARACTER SET NONE);
CREATE INDEX IDX_BIGKEY_LABEL ON BIGKEY_T (LABEL);
COMMIT;
