SET SQL DIALECT 3;
/* Customers: PK auto-indexed by system */
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID  INTEGER NOT NULL PRIMARY KEY,
  NAME         VARCHAR(100) NOT NULL,
  CITY         VARCHAR(60),
  STATUS       CHAR(1)
);

CREATE TABLE ORDERS (
  ORDER_ID     INTEGER NOT NULL PRIMARY KEY,
  CUSTOMER_ID  INTEGER NOT NULL,
  TOTAL        NUMERIC(12,2),
  CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

CREATE INDEX IDX_ORDERS_CUSTOMER_DUP ON ORDERS (CUSTOMER_ID);
CREATE INDEX IDX_CUST_NAME_CITY ON CUSTOMERS (NAME, CITY);
CREATE INDEX IDX_CUST_NAME      ON CUSTOMERS (NAME);
CREATE INDEX IDX_CUST_STATUS ON CUSTOMERS (STATUS);
CREATE INDEX IDX_CUST_CITY ON CUSTOMERS (CITY);
ALTER INDEX IDX_CUST_CITY INACTIVE;
COMMIT;

SET TERM ^ ;
EXECUTE BLOCK AS DECLARE I INTEGER = 0; BEGIN
  WHILE (I < 5000) DO BEGIN
    INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME, CITY, STATUS)
      VALUES (:I, 'CUST_' || :I, CASE MOD(:I,4) WHEN 0 THEN 'Rome' WHEN 1 THEN 'Milan' WHEN 2 THEN 'Turin' ELSE 'Naples' END,
              CASE WHEN MOD(:I,2)=0 THEN 'A' ELSE 'B' END);
    INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, TOTAL) VALUES (:I, :I, :I * 1.5);
    I = I + 1;
  END
END^
SET TERM ; ^
COMMIT;
